name: mlops-example-tensorflow-regression

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: "Install dependencies"
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: "Initialize DVC"
        run: |
          dvc init --no-scm
          git add .dvc
          git commit -m "Initialize DVC" || echo "No changes to commit"

      - name: "Train the model"
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Starting model training..."
          python model.py
          
          echo "## Model Metrics" > report.md
          cat metrics.txt >> report.md
          
          echo "\n## Model Performance" >> report.md
          echo "Model performance metrics are in the plot below." >> report.md
          
          dvc add model_results.png
          git add model_results.png.dvc
          git commit -m "Add model results to DVC" || echo "No changes to commit"
