name: mlops-example-tensorflow-regression
on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2
      
      - name: 'Set up Python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: 'Install dependencies'
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc[s3,gs,azure]  # Remplace cml par DVC (plus stable)
      
      - name: 'Train my model'
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Starting model training..."
          python model.py || echo "Model training encountered an issue, check the logs."
          
          echo "## Model Metrics" > report.md
          if [ -f metrics.txt ]; then
            cat metrics.txt >> report.md
          else
            echo "Metrics file not found. Check model.py execution." >> report.md
          fi
          
          echo "\n## Model Performance" >> report.md
          echo "Model performance metrics are on the plot below." >> report.md
          
          if [ -f model_results.png ]; then
            dvc add model_results.png  # Remplace cml-publish par DVC
            echo "![Model Results](model_results.png)" >> report.md
          else
            echo "Model results plot not found." >> report.md
          fi
          
          echo "Report generated. Check GitHub Actions logs."
