name: mlops-example-tensorflow-regression
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest  # Remove the container dependency
    steps:
      - uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Ensure you use a supported Python version
      - name: 'Install dependencies'
        run: pip install -r requirements.txt
      - name: 'Train my model'
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python model.py
          
          echo "## Model Metrics" > report.md
          cat metrics.txt >> report.md
          
          echo "\n## Model Performance" >> report.md
          echo "Model performance metrics are on the plot below." >> report.md
          
          cml-publish model_results.png --md >> report.md
          
          cml-send-comment report.md
